---
name: Net-Twitter
version: v1.0.0
author:
  - 'Chris Thompson <cpan@cthompson.com>'
abstract: Perl interface to twitter.com
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
provides:
  Net::Twitter:
    file: lib/Net/Twitter.pm
    version: !!perl/hash:version
      qv: 1
      version:
        - 1
        - 0
        - 0
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
