---
abstract: 'A perl interface to the Twitter API'
author:
  - 'Marc Mims <marc@questright.com> (@semifor on Twitter)'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter
no_index:
  directory:
    - examples
    - inc
    - src
    - t
requires:
  Carp: 0
  Crypt::SSLeay: 0.5
  Data::Visitor::Callback: 0
  DateTime: 0.51
  DateTime::Format::Strptime: 1.09
  Devel::StackTrace: 1.21
  Digest::HMAC_SHA1: 0
  Digest::SHA: 0
  Encode: 0
  File::Spec: 0
  HTML::Entities: 0
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 2.032
  List::Util: 0
  Moose: 0.9
  Moose::Exporter: 0
  Moose::Role: 0
  MooseX::Aliases: 0
  MooseX::Role::Parameterized: 0
  Net::Netrc: 0
  Net::OAuth: 0.25
  Scalar::Util: 0
  Time::HiRes: 0
  Try::Tiny: 0.03
  URI: 1.4
  URI::Escape: 0
  namespace::autoclean: 0.09
  perl: 5.8.1
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Net-Twitter
  homepage: http://github.com/semifor/Net-Twitter
  license: http://dev.perl.org/licenses/
  repository: git://github.com/semifor/Net-Twitter.git
version: 3.18003
