---
abstract: 'A interface to the Twitter API'
author:
  - 'Marc Mims <marc@questright.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Twitter
no_index:
  directory:
    - inc
    - src
    - t
recommends:
  JSON::XS: 0
requires:
  JSON::Any: 0
  Moose: 0.78
  MooseX::Traits: 0
  URI::Escape: 0
  namespace::autoclean: 0
  perl: 5.8.1
resources:
  homepage: http://github.com/semifor/Net-Twitter
  license: http://dev.perl.org/licenses/
  repository: git://github.com/semifor/Net-Twitter.git
version: 2.99000_01
