# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Twitter
version:      1.15
version_from: lib/Net/Twitter.pm
installdirs:  site
requires:
    JSON::Any:                     0
    LWP::UserAgent:                0
    Test::More:                    0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
