--- #YAML:1.0
name:                Net-Twitter
version:             1.10
abstract:            Perl interface to twitter.com
license:             ~
author:              
    - Chris Thompson <cpan@cthompson.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    JSON::Any:                     0
    LWP::UserAgent:                0
    Test::More:                    0
    URI::Escape:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
